#!/bin/sh
#if [ -z ${FOCUS+x} ]; then FOCUS=63; else FOCUS=$((FOCUS-3)); fi
#export FOCUS
FOCUS=63;

if [ -e "/etc/motioneye/camera-1.focus" ] ; then
    FOCUS=$(cat "/etc/motioneye/camera-1.focus")
fi

FOCUS=$((FOCUS+3))

if [ "$FOCUS" -gt 63 ] ; then FOCUS=63; fi

echo $FOCUS > "/etc/motioneye/camera-1.focus"

FOCUSTXT=$( printf "0x%x" $FOCUS )

echo "focus level: $FOCUS ($FOCUSTXT)"
curl "http://localhost:7999/1/config/set?text_left=Focus: $FOCUS"

i2cset -y 0 0x0c $FOCUSTXT $FOCUSTXT

